version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/owdex"
    schedule:
      interval: "monthly"
    assignees:
      - "thcrt"
    groups:
      minor-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
