# This Compose file is for development purposes.
# For a production-ready version, see https://github.com/owdex/compose

version: "3.8"

services:

  solr:
    container_name: solr
    image: solr

    volumes:
      - ./db/solr/data:/var/solr/
      - ./db/solr/configset:/owdex_configset:ro
      - ./db/solr/entrypoint.sh:/entrypoint.sh

    entrypoint:
    - /entrypoint.sh


  mongo:
    container_name: mongo
    image: mongo

    volumes:
      - ./db/mongo/data:/data/db

  frontend:
    container_name: frontend
    build: .
    
    ports:
      - 80:80
    volumes:
      - ./owdex.toml:/owdex.toml:ro
