version: "3.8"

services:

  solr:
    container_name: solr
    image: solr
    profiles: 
      - prod

    volumes:
      - ./db/solr/data:/var/solr/
      - ./db/solr/configset:/owdex_configset:ro
      - ./db/solr/entrypoint.sh:/entrypoint.sh

    entrypoint:
    - /entrypoint.sh
  
  solr-dev:
    container_name: solr
    image: solr
    profiles: 
      - dev

    ports:
      - 8983:8983
    volumes:
      - ./db/solr/data:/var/solr/
      - ./db/solr/configset:/owdex_configset:ro
      - ./db/solr/entrypoint.sh:/entrypoint.sh

    entrypoint:
      - /entrypoint.sh


  mongo:
    container_name: mongo
    image: mongo
    profiles: 
      - prod

    volumes:
      - ./db/mongo/data:/data/db
  
  mongo-dev:
    container_name: mongo
    image: mongo
    profiles: 
      - dev

    ports:
      - 27017:27017
    volumes:
      - ./db/mongo/data:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    profiles: 
      - dev

    restart: always
    ports:
      - 8081:8081


  frontend:
    container_name: frontend
    build: ./frontend
    profiles: 
      - prod

  caddy:
    container_name: cadddy
    image: caddy
    profiles:
      - prod

    ports:
      - 80:80
    volumes:
      - ./caddy_data:/data
      - ./Caddyfile:/etc/caddy/caddyfile