version: "3.8"

services:

  solr:
    container_name: solr
    image: solr

    volumes:
      - ./db/solr/data:/var/solr/
      - ./db/solr/configset:/owdex_configset:ro
      - ./db/solr/entrypoint.sh:/entrypoint.sh

    entrypoint:
    - /entrypoint.sh


  mongo:
    container_name: mongo
    image: mongo

    volumes:
      - ./db/mongo/data:/data/db


  frontend:
    container_name: frontend
    build: ./frontend
    profiles:
      - prod
    
    volumes:
      - ./owdex.toml:/owdex.toml:ro

  frontend_dev:
    container_name: frontend
    build: .
    profiles:
      - dev
    
    ports:
      - 80:80
    volumes:
      - ./owdex.toml:/owdex.toml:ro


  caddy:
    container_name: caddy
    image: caddy
    profiles:
      - prod

    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
